
-- CREATE AND USE DATABASE

CREATE DATABASE Internship_Projects
USE Internship_Projects

-- VIEW TABLE
SELECT * FROM sales_data_sample

-- Modify column name "ï»¿ORDERNUMBER" TO ORDERNUMBER for clean and easy querying 
ALTER TABLE sales_data_sample
RENAME COLUMN `ï»¿ORDERNUMBER` TO ORDERNUMBER;

-- 1. DETERMINE BUSINESS METRICS INCLUDING TOTAL: Orders, Customers Size, Countries, Quantity, Sales, Average Quantity & Sales Per order
SELECT 
	COUNT(DISTINCT ORDERNUMBER) AS TOTAL_ORDERS,
    COUNT(DISTINCT CUSTOMERNAME) AS TOTAL_CUSTOMERS,
	COUNT(DISTINCT COUNTRY) AS COUNTRIES,
	ROUND(SUM(QUANTITYORDERED),0) AS TOTAL_QUANTITY,
    ROUND(SUM(QUANTITYORDERED)/COUNT(DISTINCT ORDERNUMBER),0) AS AVERAGE_QUANTITY,
    ROUND(SUM(SALES),0) AS TOTAL_SALES,
    ROUND(SUM(SALES)/COUNT(DISTINCT ORDERNUMBER),0) AS AVERAGE_SALES
FROM sales_data_sample

-- 2.REVENUE TRENDS OVERTIME 
-- Yearly sales performance
SELECT
	YEAR_ID,
    COUNT(DISTINCT MONTH_ID) AS NUMBER_OF_MONTHS,
    ROUND(SUM(SALES),0) AS SALES,
    LAG(ROUND(SUM(SALES),0)) OVER(ORDER BY YEAR_ID) AS PREVIOUS_YEAR_SALES
FROM SALES_DATA_SAMPLE
GROUP BY YEAR_ID
ORDER BY  YEAR_ID DESC

-- Comparison between 2004 and 2005 over the first five months
SELECT YEAR_ID, ROUND(SUM(SALES)) AS SALES_IN_5MONTHS FROM sales_data_sample WHERE YEAR_ID IN (2004,2005) AND MONTH_ID BETWEEN 1 AND 5 GROUP BY YEAR_ID

-- Quaterly trends
SELECT
	QTR_ID,
    ROUND(SUM(SALES),0) AS SALES
FROM sales_data_sample
GROUP BY QTR_ID
ORDER BY ROUND(SUM(SALES),0) DESC
 
 -- Monthly sales performance
SELECT
	MONTH_ID,
    ROUND(SUM(SALES),0) AS SALES
FROM sales_data_sample
GROUP BY MONTH_ID
ORDER BY ROUND(SUM(SALES),0) DESC;

-- 3. REGIONAL SALES PERFORMANCE
-- Update Table where territory is Japan to APAC
SET SQL_SAFE_UPDATES = 0;

UPDATE SALES_DATA_SAMPLE
SET TERRITORY = 'APAC'
WHERE TERRITORY = 'Japan'

-- Territorial performance by sales and countries covered
SELECT 
	TERRITORY, 
    ROUND(SUM(SALES),0) AS SALES,
	COUNT(DISTINCT COUNTRY) AS COUNTRIES
FROM SALES_DATA_SAMPLE
GROUP BY TERRITORY
ORDER BY ROUND(SUM(SALES),0) DESC;

-- Top performing country
SELECT 
	COUNTRY,
	ROUND(SUM(SALES),0) AS SALES,
	COUNT(DISTINCT ORDERNUMBER) AS TOTAL_ORDERS,
	COUNT(DISTINCT CUSTOMERNAME) AS NUMBER_OF_CUSTOMERS
FROM sales_data_sample
GROUP BY COUNTRY
ORDER BY ROUND(SUM(SALES),0) DESC;

-- 4. TOP PERFORMING PRODUCTS
SELECT 
	PRODUCTLINE,
	ROUND(AVG(DISTINCT PRICEEACH),0) AS AVERAGE_PRICEEACH,
    ROUND(SUM(SALES),0) AS SALES,
    SUM(QUANTITYORDERED) AS QUANTITY,
    COUNT(DISTINCT CUSTOMERNAME) AS CUSTOMERS,
	COUNT(DISTINCT COUNTRY) AS COUNTRIES
FROM sales_data_sample
GROUP BY PRODUCTLINE
ORDER BY SALES DESC;

-- 5. DELIVERY STATUS EVALUATION
SELECT 
	STATUS, 
	COUNT(DISTINCT ORDERNUMBER) AS COUNT,
    ROUND(SUM(QUANTITYORDERED),0) AS QUANTITY,
    ROUND(SUM(SALES),0) AS SALES
FROM sales_data_sample
GROUP BY STATUS

-- 6. ASSESMENT OF CUSTOMER BEHAVIOUR
-- Top 10 high purchasing customers

-- Customer segmentation into New, Returning, and Loyal customers based on number of purchases
WITH CUSTOMER_SEGMENTATION AS (
								SELECT 
									DISTINCT CUSTOMERNAME,
                                    COUNT(DISTINCT ORDERNUMBER) AS PURCHASES,
                                    CASE
										WHEN COUNT(DISTINCT ORDERNUMBER) = 1 THEN 'New'
                                        WHEN COUNT(DISTINCT ORDERNUMBER) BETWEEN 2 AND 3 THEN 'Returning'
                                        ELSE 'Loyal'
									END AS CUSTOMER_CATEGORY
								FROM sales_data_sample
                                GROUP BY CUSTOMERNAME)
SELECT 
	CUSTOMER_CATEGORY, 
    COUNT(*) AS CUSTOMERSIZE
FROM CUSTOMER_SEGMENTATION
GROUP BY CUSTOMER_CATEGORY
                                

